### ISSUE TITLE
`blocking` - an R package for blocking based on approximate nearest neighbours and graphs

### ISSUE THREAD

**Issue by BERENZ** [OlivierBinette/Awesome-Entity-Resolution#1]
Hi! Thanks for an interesting list of resources for entity resolution! 

I am writing to let you know that I am developing a small R package called [`blocking`](https://github.com/ncn-foreigners/blocking) which allows you to block records based on approximate nearest neighbours algorithms (currently using `RcppAnnoy`, `RcppHNSW` and `mlpack::lsh`) and graphs (`igraph`). So maybe it will fit into your list :)

**Comment by OlivierBinette** [comment]
@BERENZ Thanks for sharing! Adding this to the list.
